version: 2

always_pending:
  title_regex: '(WIP|wip)'
  explanation: 'This PR is a work in progress...'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:|:\+1:)'
  conditions:
    files:
    - "*.go" # only review source
    - ".pullapprove.yml" # and this file

groups:
  owner:
    required: 1
    users:
    - phylake
    reset_on_push:
      enabled: true
    reset_on_reopened:
      enabled: true
  reviewers:
    required: 1
    users:
    - davepersing
    - gregoryfischer
    - jfieber
