# This image's lineage
# golang:1.6.2
#   buildpack-deps:jessie-scm
#     buildpack-deps:jessie-curl
#       debian:jessie
#         scratch
FROM golang:1.6.2

RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega

CMD ginkgo -r -p
