#!/bin/sh
cat << EOF

Linux performance commands http://nflx.it/1PXHO3h
uptime
dmesg | tail
vmstat 1
mpstat -P ALL 1
pidstat 1
iostat -xz 1
free -m
sar -n DEV 1
sar -n TCP,ETCP 1
top

Log paths (in order)
/var/log/cloud-init-output.log
/var/log/cfn-init-cmd.log
/var/log/porter.log
EOF
